# Урок 4. Видеоурок. Визуализация данных в Matplotlib.

## Тема “Задания на повторение материала”

In [1]:
import numpy as np

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
display(a.reshape(1, 12), a.reshape(2, 6), a.reshape(3, 4), a.reshape(4, 3), a.reshape(6, 2))

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
display(a.reshape(1, -1), a.reshape(2, -1), a.reshape(3, -1), a.reshape(-1, 3), a.reshape(-1, 2))

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [5]:
a.reshape(12, 1).ndim  # numpy считает, что нет

2

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [6]:
x = np.random.randn(3, 4)
x

array([[-0.55662527, -0.60805876,  1.77690197, -0.00761248],
       [-0.28904478,  0.7191433 , -0.84618277, -1.05587871],
       [ 0.10167746,  1.68693707, -0.4103069 ,  0.004549  ]])

In [7]:
x.flatten()

array([-0.55662527, -0.60805876,  1.77690197, -0.00761248, -0.28904478,
        0.7191433 , -0.84618277, -1.05587871,  0.10167746,  1.68693707,
       -0.4103069 ,  0.004549  ])

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [8]:
a = np.arange(20, 0, -2)
display(a, a.ndim, a.shape)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

1

(10,)

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [9]:
b = a.reshape(1, -1)
display(b, b.ndim, b.shape)  # Разница в геометрии

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

2

(1, 10)

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [10]:
a, b = np.zeros((2, 2)), np.ones((3, 2))
v = np.vstack((a, b))
assert v.size == 10
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [11]:
a = np.arange(12)
A = a.reshape(4, -1)
At = A.T
B = A @ At
display(B, B.shape)

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

(4, 4)

In [12]:
if np.linalg.matrix_rank(B) < B.shape[0]:
    print("Ранг маловат для вычисления обратной матрицы")

Ранг маловат для вычисления обратной матрицы


10.  Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [13]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [14]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [15]:
C = c.reshape(4,4)
D = B + C * 10
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [16]:
D_det = np.linalg.det(D)
D_rank = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)
display(D_det, D_rank, D_inv)

-28511999.999999944

4

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [17]:
D_inv = (D_inv > 0).astype(int)
D_inv

array([[1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]])

In [18]:
E = np.where(D_inv, B, C)

In [19]:
display(B, C, E)

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])